### ISSUE TITLE
Path to pdf.css is broken

### ISSUE THREAD

**Issue by dvrensk** [adrianvlupu/C4Builder-Demo#1]
Hello! Thanks for a wonderful tool and a very helpful example that's really good for getting things running.

I've run into some problems on macos and will file tickets here just as documentation, and hopefully I will get around to submitting PRs for them myself.  If not, at least they're documented and the next clueless user can get some solace in not being alone.

So, first ticket:

## What I did

* installed C4Builder
* cloned the repo from Github && `cd C4Builder-Demo`
* ran `c4builder`

## Expected result

Among other things, a PDF in `./docs`

## Actual result

`c4builder` never exits.  This is the output:

```
building documentation in ./docs
parsed 7 folders
generating images
processed 8/8 images
generating markdown files
processed 7/7 files
generating docsify site
generating complete pdf file
[Error: ENOENT: no such file or directory, open 'C:\Projects\C4-Builder\pdf.css'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Projects\\C4-Builder\\pdf.css'
}
built in 6.013 seconds

to view the generated website run
> c4builder site
```

## Workaround

```bash
$ dir=$(asdf which c4builder)
$ cp $(dirname $dir)/../lib/node_modules/c4builder/pdf.css .
```

And update `.c4builder` to include `"pdfCss": "./pdf.css"`.

**Comment by adrianvlupu** [comment]
Hi ! You are right. There is no need for the `pdfCss` config there. It will use the default if the linke is removed.
